//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT2_Nhom04_QuanLyQuanCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }
    
        public string maHD { get; set; }
        public string maNV { get; set; }
        public string maKH { get; set; }
        public string maBan { get; set; }
        public System.DateTime ngayLapHD { get; set; }
        public int diemTL { get; set; }
        public double giamGia { get; set; }
        public double chiPhiKhac { get; set; }
        public double tongTien { get; set; }
    
        public virtual BANCF BANCF { get; set; }
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
