//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT2_Nhom04_QuanLyQuanCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string maKH { get; set; }
        public string HoTenKH { get; set; }
        public Nullable<System.DateTime> namSinhKH { get; set; }
        public string diaChiKH { get; set; }
        public string emailKH { get; set; }
        public string gioiTinhKH { get; set; }
        public string sdtKH { get; set; }
        public int diemTL { get; set; }
        public bool LoaiKH { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
