//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT2_Nhom04_QuanLyQuanCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUVUC
    {
        public KHUVUC()
        {
            this.BANCFs = new HashSet<BANCF>();
        }
    
        public string maKV { get; set; }
        public string tenKV { get; set; }
        public bool trangThai { get; set; }
    
        public virtual ICollection<BANCF> BANCFs { get; set; }
    }
}
