//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT2_Nhom04_QuanLyQuanCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }
    
        public string maSP { get; set; }
        public string maLSP { get; set; }
        public string tenSP { get; set; }
        public string phoBienSP { get; set; }
        public byte[] hinhAnhSP { get; set; }
        public double giaSP { get; set; }
    
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
